
FROM node:alpine as builder

WORKDIR /usr/src/app
COPY package.json ./

RUN npm install 
RUN npm install react-scripts@4.0.3 -g

COPY ./ ./

EXPOSE 3000
CMD ["npm","run","build"]

FROM nginx
EXPOSE 80
COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /usr/src/app/build usr/share/nginx/html 

